name: Generate Snake Animation

on:
  schedule: # Runs at 1:00 AM UTC every day
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
      - name: Generate Snake Animation and Push to Output Branch
        run: |
          mkdir -p dist
          cp dist/snake.svg dist/snake.html

